# site settings
title: Happy Birthday Becky! 
subtitle: 
email: 
description: ...Here are some thoughtful/playful notes from people who love you.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://happybirthdaybecky.github.io" # the base hostname & protocol for your site
author:
street_address: 
city: 
state: 
zip_code: 
country:
phone: 

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url: 
instagram_url: 
linkedin_url: 
pinterest_url:
slack_url:
twitter_url: 

# build settings
markdown: kramdown

sass:
  style: compressed
